version: '3.8'

services:
  almacen:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    environment:
      - PYTHONPATH=/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/productos"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 